version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/chatnodeprod
permissions:
  - object: /home/ec2-user/chatnodeprod
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: afterinstall.sh
      timeout: 100
        #BeforeInstall:
        # - location: beforeinstall.sh
        #  timeout: 100
        #  ApplicationStart:
        #    - location: applicationstart.sh
        #     timeout: 100
